# Generated by Django 4.0.5 on 2025-01-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('mail_manager', models.CharField(choices=[('sendgrid', 'SendgridEmailManager'), ('zepto', 'ZeptoEmailManager'), ('smtp', 'SMTPEmailManager')], max_length=10)),
                ('config', models.JSONField()),
            ],
        ),
    ]
